### ISSUE TITLE
What is HTML?

### ISSUE THREAD

**Issue by dyrnade** [dyrnade/copytrader#109]

**Comment by sbatu96** [comment]
"html" tarayıcının anlayabildiği ve kullanıcının gözüyle gördüğü şeylerin tasarımını yaptığımız dildir.

**Comment by EyupsaN3400** [comment]
(html) basit kod yapıları olan etiketler ve nitelikler kullanılarak web sayfaları şekillendirilebilir. HTML için aslında bir web sitesinin iskeleti denilebilir.
