### ISSUE TITLE
What is a Web Application?

### ISSUE THREAD

**Issue by dyrnade** [dyrnade/copytrader#98]
Explain briefly.

**Comment by EyupsaN3400** [comment]
Erişimi internet üzerinden sağlanan programlardır.

Web Application, internet tarayıcılarını istemcisi olarak kullanan, seçilmiş işlevleri yerine getiren bilgisayar programları olarak da bilinmektedir. İstemci bu bağlamda, sunucu bilgisayarlar üzerinden hizmet alan, kullanıcı bilgisayarlarını ifade etmektedir.

Web Application’ları genel itibariyle, bir tarayıcı üzerinden kullanıcılarının web sunucusuna bağlanmalarına yardımcı olan köprü görevi görmektedir.

Web Application Kullanım Alanları
Örmek:
1- Sosyal Medya
2- E Ticaret
3- Bilgilendirici From Web Uygulamaları

**Comment by dyrnade** [comment]
Dankeschon
